version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1td4yof98sein"
s3_prefix = "sam-app-hello-world"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
