AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    MemorySize: 128
    Timeout: 3

Resources:  
  HelloWorldLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.handler
      Runtime: nodejs14.x
      CodeUri: ./src
      Events:
        HelloWorldApiGateway:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

Outputs:
  HelloWorldAPI:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"